version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hr-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: humanrsc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d humanrsc"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hr-network

volumes:
  postgres_data:

networks:
  hr-network:
    driver: bridge